Prgm1: main.o readin.o userInputHandler.o print.o 
		gcc -o Prgm1 main.o readin.o userInputHandler.o print.o

main.o: main.c
		gcc -c -Wall main.c

readin.o: readin.c
		gcc -c -Wall readin.c 

userInputHandler.o: userInputHandler.c
		gcc -c -Wall userInputHandler.c

print.o: print.c
		gcc -c -Wall print.c 
